### ISSUE TITLE
Vercel uses 2.0.0+incompatible

### ISSUE THREAD

**Issue by han-so1omon** [fauna/faunadb-go#105]
Vercel supports Go, and FaunaDB + Vercel is a promising setup. However, Vercel uses a go.mod file to setup the runtime environment. As per other issues, such as #90, the go mod dependency setup produces some version issues.

The main issue is that Vercel grabs version 2.0.0+incompatible from 2018. I can't the docs for this version. Could you provide link to the docs. Otherwise what is the course of action so that go mod grabs the current version?

**Comment by ldez** [comment]
Related to  #97
