### ISSUE TITLE
Inquiry about new godoc site

### ISSUE THREAD

**Issue by FriendlyUser** [fauna/faunadb-go#113]
When I click the link to go to the future version of godoc, I see that there is no documentation visible.

https://pkg.go.dev/github.com/fauna/faunadb-go/faunadb

Seems like there is a license issue or something.

**Comment by n400** [comment]
Thank you! We have an internal ticket to fix this.

**Comment by vadimLF** [comment]
This is fixed with [this commit](https://github.com/fauna/faunadb-go/commit/8c265b9576e5b1e8ec6dcc48ab62202667fd373f)

**Comment by n400** [comment]
Closing this. Please let us know if you are still experiencing the issue.
