### ISSUE TITLE
LICENSE file not detected correctly by new go doc site

### ISSUE THREAD

**Issue by mscno** [fauna/faunadb-go#125]
The new documentation site for go  (pkg.go.dev) does not detect the LICENSE file correctly, causing documenation to not be displayed. 

Missing docs: https://pkg.go.dev/github.com/fauna/faunadb-go/v3/faunadb

The License is MPL-2.0, but somehow **pkg.go.dev** does not detect this.

More info: https://pkg.go.dev/license-policy

**Comment by n400** [comment]
Thank you! We have an internal ticket to fix this.

**Comment by parkhomenko** [comment]
hi @mscno ,
could you give a bit more details on what is missing here:
https://pkg.go.dev/github.com/fauna/faunadb-go/v3/faunadb

I've checked the output generated by the license tool that is used for license detection as:
```
package main

import "fmt"
import "io/ioutil"
import "github.com/google/licensecheck"

func main() {
  data, _ := ioutil.ReadFile("./license")
  cov := licensecheck.Scan(data)
  fmt.Printf("%.1f%% of text covered by licenses:\n", cov.Percent)
  for _, m := range cov.Match {
    fmt.Printf("%s at [%d:%d] IsURL=%v\n", m.ID, m.Start, m.End, m.IsURL)
  }
}
```

it returns that it finds a correct license:
```
100.0% of text covered by licenses:
MPL-2.0 at [0:546] IsURL=false
```
