### ISSUE TITLE
Response error 401. Errors: [](unauthorized): Unauthorized, details: []

### ISSUE THREAD

**Issue by axk2** [fauna/faunadb-go#150]
i've just got this error following the example. i've created a server key for this code

https://docs.fauna.com/fauna/current/drivers/go

but i can't read or create data

Response error 401. Errors: [](unauthorized): Unauthorized, details: []

always is the same error, i am using v4 and golang v1.16

**Comment by fireridlle** [comment]
@axk2 which region group you have used during db creating process?

**Comment by axk2** [comment]
i chose United States, i am from south america, chile
i can't do "Run as" too
i didn't try that.
why can't i use my secret key in shell or in my computer?

**Comment by fireridlle** [comment]
You need to pass US domain (db.us.fauna.com) together with a secret

https://docs.fauna.com/fauna/current/api/fql/region_groups

**Comment by axk2** [comment]
thanks, that's it. i would give you a tip, but i am poor :c
