### ISSUE TITLE
go get command fails with "no buildable Go source files"

### ISSUE THREAD

**Issue by tleyden** [fauna/faunadb-go#42]
I ran into an error running `go get`:

```
$ go get github.com/fauna/faunadb-go
package github.com/fauna/faunadb-go: no buildable Go source files in /$GOPATH/src/github.com/fauna/faunadb-go
```

This works:

```
$ go get github.com/fauna/faunadb-go/...
```

To have `go get github.com/fauna/faunadb-go` work as stated, you'd need to move everything from `/fauna/*` up a directory into the root.

**Comment by erickpintor** [comment]
Thanks for the feedback. I guess `go get github.com/fauna/faunadb-go/fauna` also works.

**Comment by erickpintor** [comment]
The hello tutorial has been fixed. Thanks for the feedback.
