### ISSUE TITLE
Tutorial example broken

### ISSUE THREAD

**Issue by tleyden** [fauna/faunadb-go#43]
This example from the [tutorial](https://fauna.com/tutorials/hello) isn't valid Go syntax:

```
func main() {
        
        res, err := client.Query(f.Concat(["Hello", "World"], " "))
        if err != nil {
                panic(err)
        }

        fmt.Println(res)
}

```

I changed it to this and it worked:

```
	res, err := client.Query(f.Concat([]string{"Hello", "World"}))
	if err != nil {
		panic(err)
	}

	fmt.Println(res)
```

**Comment by erickpintor** [comment]
Thanks for pointing it out. You could also use `f.Arr{"Hello", "Word"}` for some syntax sugar.

**Comment by erickpintor** [comment]
The hello tutorial has been fixed. Thanks for the feedback.
