### ISSUE TITLE
Documentation error on f.RefCollection

### ISSUE THREAD

**Issue by NHibiki** [fauna/faunadb-go#76]
In the godocs, collections are referred by `f.RefCollection("someRef")` Method. However, in practice, `f.Ref("collections/someRef")` is the right way to get the reference of a specific collection. Is it miss-documented?

**Comment by kusanagi-jin** [comment]
I got the same error. it seems that the tutorial is outdated.
https://docs.fauna.com/fauna/current/drivers/go

**Comment by marrony** [comment]
`f.Ref("collections/someRef")` is a deprecated way to create references, `f.RefCollection("someRef")` should be used instead
