### ISSUE TITLE
go get not getting latest version - v2.9.0

### ISSUE THREAD

**Issue by rof20004** [fauna/faunadb-go#77]
I am trying to get faunadb-go with go get ./... but it always get this:

```
github.com/fauna/faunadb-go v2.0.0+incompatible // indirect
gopkg.in/fauna/faunadb-go.v2 v2.0.0
```

**Comment by leonidboykov** [comment]
@rof20004 you can try to get the latest version by providing a tag

    go get github.com/fauna/faunadb-go@2.9.0

but thanks to Go Modules versions _must_ have `v` prefix.

That would be nice to have a `v2.9.0` tag for the latest version.

**Comment by rof20004** [comment]
@leonidboykov Thanks for information.

I tried this and got same version, I think the problem is like you explained, the v prefix.

**Comment by camilopayan** [comment]
This is still happening with the `v2.10.0` tag unfortunately. I'm not sure how to import the module so that the right version lands in `go.mod`. I've tried something like `import "github.com/fauna/faunadb-go/v2/faunadb"` but that doesn't function. Any insights into how to import this module to get the latest?

**Comment by trevorsibanda** [comment]
@camilopayan  try using  in the meantime, whilst I sort this out.
`go get gopkg.in/fauna/faunadb-go.v2`

`import "gopkg.in/fauna/faunadb-go.v2"`

**Comment by camilopayan** [comment]
Thanks for the response. For now I'm sticking with 2.0, unfortunately.

When I tried `import "gopkg.in/fauna/faunadb-go.v2"` I got this message:

```
build command-line-arguments: cannot load gopkg.in/fauna/faunadb-go.v2: module gopkg.in/fauna/faunadb-go.v2@latest found (v2.0.0), but does not contain package gopkg.in/fauna/faunadb-go.v2
make: *** [build] Error 1
```

**Comment by exul** [comment]
The tag is now correct (having the v prefix), but the go.mod file is still wrong. According to https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning the first line has to be `github.com/fauna/faunadb-go/v2` instead of `github.com/fauna/faunadb-go`.
With the current version this leads to the followin error:

```
go get github.com/fauna/faunadb-go@v2.10.0
go: finding github.com/fauna/faunadb-go v2.10.0
go get github.com/fauna/faunadb-go@v2.10.0: github.com/fauna/faunadb-go@v2.10.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

**Comment by trevorsibanda** [comment]
@exul that is correct. We have a release scheduled soon which will address this and update the documentation. > 2.10.0 all releases will follow go modules import compatibility rules.

See https://github.com/fauna/faunadb-go/tree/fix-semver

**Comment by mwildehahn** [comment]
```
➜ go get github.com/fauna/faunadb-go@v2
go: extracting github.com/fauna/faunadb-go v2.0.0+incompatible
```

```
➜ go get gopkg.in/fauna/faunadb-go.v2
go: extracting gopkg.in/fauna/faunadb-go.v2 v2.0.0
```

both of these install v2.0.0 which seems to be the version from 2018 without functions for `Collection` among other things.

**Comment by mwildehahn** [comment]
Ah I guess you can use `Class` in place of `Collection` for the time being. FWIW this is really confusing and frustrating for someone just trying to get started with fauna.

**Comment by StarpTech** [comment]
Hi, I have the same issue as @mwildehahn described.

**Comment by StarpTech** [comment]
The current approach is incompatible with go modules because faunadb has a `.mod` file and a version higher than v2.

See: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by yonnic** [comment]
this issue cost me nearly 3 hours to find and it still persists in the latest version. 
go.mod loads by default version 2.0.0 from 2018 with nonexisting f.Collection and the latest v2.12.1 version is v1.0.1-0 in go.mod
