### ISSUE TITLE
Fetch array of items

### ISSUE THREAD

**Issue by kidandcat** [fauna/faunadb-go#81]
How to fetch an array of items and unmarshal them to struct?

I tried using a Lambda, but I couldn't unmarshal the result to an array of my structs.

I ended up with this, but I guess this is doing too many requests to the DB, yes?

```go
func (db DB) Users() ([]User, error) {
	res, err := db.client.Query(f.Paginate(f.Match(f.Index("all_users")), f.Size(99999)))
	if err != nil {
		return nil, err
	}

	var refs []f.RefV
	res.At(f.ObjKey("data")).Get(&refs)

	var users []User
	for _, ref := range refs {
		res, err := db.client.Query(f.Get(ref))
		if err != nil {
			return nil, err
		}
		var user User
		res.At(f.ObjKey("data")).Get(&user)
		users = append(users, user)
	}

	return users, nil
}
```

**Comment by trevorsibanda** [comment]
Yes that would unnecessarily be too many queries.

Rewrite the query to `f.Select("data", f.Map(f.Paginate(f.Match(f.Index("all_users"))), f.Lambda("x", f.Get(f.Var("x"))))` and unmarshall to f.ArrayV

**Comment by kidandcat** [comment]
Thanks! Let me suggest to put that on the docs because I couldn't find any solution like that after searching everywhere (forums, stackoverflow, official docs, even faunadb-go tests)

**Comment by marrony** [comment]
Instead of unmarshall to f.ArrayV you can unmarshall to your type directly, the driver supports this operation

**Comment by kidandcat** [comment]
If I do this:

```
func (db DB) Users() ([]User, error) {
	res, err := db.client.Query(f.Select("data", f.Map(f.Paginate(f.Match(f.Index("all_users"))), f.Lambda("x", f.Get(f.Var("x"))))))
	if err != nil {
		return nil, err
	}

	var users []User
	res.At(f.ObjKey("data")).Get(&users)

	return users, nil
}
```

users is null

**Comment by marrony** [comment]
You are doing the `Select` in the wrong place, you should move it to inside `Map` to extract the `data` field of the return of `Get`

**Comment by marrony** [comment]
Something like
```
Map(
  Paginate(...),
  Lambda(“x”, Select(“data”, Get(Var(“x”))))
)
```

**Comment by kidandcat** [comment]
Working perfectly now, I let the code here for other people:

```go
func (db DB) Users() ([]User, error) {
	res, err := db.client.Query(f.Map(f.Paginate(f.Match(f.Index("all_users"))), f.Lambda("x", f.Select("data", f.Get(f.Var("x"))))))
	if err != nil {
		return nil, err
	}

	var users []User
	res.At(f.ObjKey("data")).Get(&users)

	return users, nil
}
```
