### ISSUE TITLE
Error when setting time to live on Create

### ISSUE THREAD

**Issue by camilopayan** [fauna/faunadb-go#83]
In the documentation for `Create` I can see that it supports a `TTL` parameter, which takes a Fauna Timestamp object: https://docs.fauna.com/fauna/current/api/fql/functions/create

In the [documentation for Timestamps](https://docs.fauna.com/fauna/current/api/fql/types#timestamp), it says the code to use for the Go library is `faunadb.Time` but when I do so, I get an error saying that `faunadb.Time is not a type`.

I can't find `Time` in the code, but I have found some similar things, like TimeV. Would that be the type to use for timestamps? I see that it's basically just a wrapper around the Go stdlib `time.Time` object.

**Comment by rts-rob** [comment]
Hi @camilopayan - I suggest avoiding using the `TimeV` type directly in your code. Instead, call `f.Time()` as a function, passing a ISO 8601 offset date/time (e.g., _"2006-01-02T15:04:05Z"_). That returns an `f.Expr` object with the Timestamp that you can use in the params for `Create()` or as an argument to the other Date/Time functions in FQL.

```go
ts := f.Time("2006-01-02T15:04:05Z")
```
